### ISSUE TITLE
Use better shader implementations, but I really like it.

### ISSUE THREAD

**Issue by Noemata** [Portles/MetallicView#1]
Very nice!  My only caveat is the choice of shaders. Not all would be considered accurate.  There are better implementations out there for contrast, or turning an image monochrome (some of the others are also too simple).  A correct shader for converting an image to black and white adjusts for the eyes differing sensitivity to R,G,B.  Our eyes are least sensitive to blue, so the shader code needs to adjust for that.  A monochrome shader would be something like 0.299R + 0.587G + 0.114B = gray level.  Contrast adjustments typically have a few parameters.  And so forth.

One other note, on some systems, RBG levels are already pre-emphasized so you just divide by 255. This is a good start:
https://stackoverflow.com/questions/17615963/standard-rgb-to-grayscale-conversion

**Comment by Portles** [comment]
Thanks for you explanation. I don't consider to improve or change any code in this repo.
